name: Build KingsSMP-Rituals

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -e -DskipTests clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: KingsSMP-Rituals-jar
          path: target/*-shaded.jar
